// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package order

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Product struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Author               string   `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Genre                string   `protobuf:"bytes,3,opt,name=genre,proto3" json:"genre,omitempty"`
	Pages                int32    `protobuf:"varint,4,opt,name=pages,proto3" json:"pages,omitempty"`
	Publication          string   `protobuf:"bytes,5,opt,name=publication,proto3" json:"publication,omitempty"`
	Price                float64  `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	Quantity             int32    `protobuf:"varint,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Product) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Product) GetGenre() string {
	if m != nil {
		return m.Genre
	}
	return ""
}

func (m *Product) GetPages() int32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *Product) GetPublication() string {
	if m != nil {
		return m.Publication
	}
	return ""
}

func (m *Product) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Product) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type Location struct {
	Address1             string   `protobuf:"bytes,1,opt,name=address1,proto3" json:"address1,omitempty"`
	Address2             string   `protobuf:"bytes,2,opt,name=address2,proto3" json:"address2,omitempty"`
	City                 string   `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	State                string   `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	PostalCode           string   `protobuf:"bytes,5,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Country              string   `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{1}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetAddress1() string {
	if m != nil {
		return m.Address1
	}
	return ""
}

func (m *Location) GetAddress2() string {
	if m != nil {
		return m.Address2
	}
	return ""
}

func (m *Location) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Location) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Location) GetPostalCode() string {
	if m != nil {
		return m.PostalCode
	}
	return ""
}

func (m *Location) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

type Customer struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Lastname             string    `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Email                string    `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Location             *Location `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Phone                string    `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Customer) Reset()         { *m = Customer{} }
func (m *Customer) String() string { return proto.CompactTextString(m) }
func (*Customer) ProtoMessage()    {}
func (*Customer) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{2}
}

func (m *Customer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Customer.Unmarshal(m, b)
}
func (m *Customer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Customer.Marshal(b, m, deterministic)
}
func (m *Customer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Customer.Merge(m, src)
}
func (m *Customer) XXX_Size() int {
	return xxx_messageInfo_Customer.Size(m)
}
func (m *Customer) XXX_DiscardUnknown() {
	xxx_messageInfo_Customer.DiscardUnknown(m)
}

var xxx_messageInfo_Customer proto.InternalMessageInfo

func (m *Customer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Customer) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *Customer) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Customer) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Customer) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type OrderGRPCMessage struct {
	Products             []*Product `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Customer             *Customer  `protobuf:"bytes,2,opt,name=customer,proto3" json:"customer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *OrderGRPCMessage) Reset()         { *m = OrderGRPCMessage{} }
func (m *OrderGRPCMessage) String() string { return proto.CompactTextString(m) }
func (*OrderGRPCMessage) ProtoMessage()    {}
func (*OrderGRPCMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{3}
}

func (m *OrderGRPCMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderGRPCMessage.Unmarshal(m, b)
}
func (m *OrderGRPCMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderGRPCMessage.Marshal(b, m, deterministic)
}
func (m *OrderGRPCMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderGRPCMessage.Merge(m, src)
}
func (m *OrderGRPCMessage) XXX_Size() int {
	return xxx_messageInfo_OrderGRPCMessage.Size(m)
}
func (m *OrderGRPCMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderGRPCMessage.DiscardUnknown(m)
}

var xxx_messageInfo_OrderGRPCMessage proto.InternalMessageInfo

func (m *OrderGRPCMessage) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *OrderGRPCMessage) GetCustomer() *Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

type OrderID struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderID) Reset()         { *m = OrderID{} }
func (m *OrderID) String() string { return proto.CompactTextString(m) }
func (*OrderID) ProtoMessage()    {}
func (*OrderID) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{4}
}

func (m *OrderID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderID.Unmarshal(m, b)
}
func (m *OrderID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderID.Marshal(b, m, deterministic)
}
func (m *OrderID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderID.Merge(m, src)
}
func (m *OrderID) XXX_Size() int {
	return xxx_messageInfo_OrderID.Size(m)
}
func (m *OrderID) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderID.DiscardUnknown(m)
}

var xxx_messageInfo_OrderID proto.InternalMessageInfo

func (m *OrderID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Product)(nil), "order.Product")
	proto.RegisterType((*Location)(nil), "order.Location")
	proto.RegisterType((*Customer)(nil), "order.Customer")
	proto.RegisterType((*OrderGRPCMessage)(nil), "order.OrderGRPCMessage")
	proto.RegisterType((*OrderID)(nil), "order.OrderID")
}

func init() {
	proto.RegisterFile("order.proto", fileDescriptor_cd01338c35d87077)
}

var fileDescriptor_cd01338c35d87077 = []byte{
	// 413 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0xdf, 0x8a, 0x13, 0x31,
	0x14, 0xc6, 0x49, 0x77, 0xdb, 0x4e, 0xcf, 0x48, 0x95, 0x20, 0x1a, 0x7b, 0xe3, 0x30, 0x57, 0x45,
	0x61, 0xc1, 0x0a, 0xbe, 0xc0, 0x2c, 0xca, 0x82, 0xe2, 0x12, 0x1f, 0x40, 0xb2, 0x93, 0x43, 0x37,
	0x38, 0x9d, 0x8c, 0x49, 0x46, 0xd8, 0xe7, 0xf0, 0x21, 0x7c, 0x04, 0x5f, 0x4f, 0x72, 0x92, 0x19,
	0xcb, 0xde, 0xe5, 0x77, 0xfe, 0xe5, 0xfb, 0x4e, 0x02, 0xa5, 0x75, 0x1a, 0xdd, 0xd5, 0xe0, 0x6c,
	0xb0, 0x7c, 0x49, 0x50, 0xff, 0x65, 0xb0, 0xbe, 0x75, 0x56, 0x8f, 0x6d, 0xe0, 0xcf, 0x61, 0x19,
	0x4c, 0xe8, 0x50, 0xb0, 0x8a, 0xed, 0x37, 0x32, 0x01, 0x7f, 0x01, 0x2b, 0x35, 0x86, 0x7b, 0xeb,
	0xc4, 0x82, 0xc2, 0x99, 0x62, 0xf5, 0x11, 0x7b, 0x87, 0xe2, 0x22, 0x55, 0x13, 0xc4, 0xe8, 0xa0,
	0x8e, 0xe8, 0xc5, 0x65, 0xc5, 0xf6, 0x4b, 0x99, 0x80, 0x57, 0x50, 0x0e, 0xe3, 0x5d, 0x67, 0x5a,
	0x15, 0x8c, 0xed, 0xc5, 0x92, 0x3a, 0xce, 0x43, 0xd4, 0xe7, 0x4c, 0x8b, 0x62, 0x55, 0xb1, 0x3d,
	0x93, 0x09, 0xf8, 0x0e, 0x8a, 0x9f, 0xa3, 0xea, 0x83, 0x09, 0x0f, 0x62, 0x4d, 0x03, 0x67, 0xae,
	0xff, 0x30, 0x28, 0x3e, 0xdb, 0xdc, 0xbe, 0x83, 0x42, 0x69, 0xed, 0xd0, 0xfb, 0x77, 0x59, 0xfd,
	0xcc, 0x67, 0xb9, 0x43, 0xb6, 0x30, 0x33, 0xe7, 0x70, 0xd9, 0xc6, 0xe1, 0xc9, 0x03, 0x9d, 0xa3,
	0x14, 0x1f, 0x54, 0x40, 0xb2, 0xb0, 0x91, 0x09, 0xf8, 0x6b, 0x28, 0x07, 0xeb, 0x83, 0xea, 0xbe,
	0xb7, 0x56, 0x63, 0xb6, 0x00, 0x29, 0xd4, 0x58, 0x8d, 0x5c, 0xc0, 0xba, 0xb5, 0x63, 0x1f, 0xdc,
	0x03, 0x79, 0xd8, 0xc8, 0x09, 0xeb, 0xdf, 0x0c, 0x8a, 0x66, 0xf4, 0xc1, 0x9e, 0xd0, 0xc5, 0x1b,
	0x7b, 0x75, 0x9a, 0x76, 0x4c, 0xe7, 0xa8, 0xb0, 0x53, 0x3e, 0x50, 0x3c, 0x2b, 0x9c, 0x38, 0xaa,
	0xc1, 0x93, 0x32, 0xdd, 0xb4, 0x66, 0x02, 0xfe, 0x16, 0x8a, 0x2e, 0x7b, 0x27, 0x99, 0xe5, 0xe1,
	0xe9, 0x55, 0x7a, 0xdd, 0x69, 0x25, 0x72, 0x2e, 0xa0, 0xdd, 0xde, 0xdb, 0x7e, 0x12, 0x9d, 0xa0,
	0xfe, 0x01, 0xcf, 0xbe, 0xc6, 0x8e, 0x4f, 0xf2, 0xb6, 0xf9, 0x82, 0xde, 0xab, 0x23, 0xf2, 0x37,
	0x50, 0x0c, 0xe9, 0x33, 0x78, 0xc1, 0xaa, 0x8b, 0x7d, 0x79, 0xd8, 0xe6, 0xb1, 0xf9, 0x8f, 0xc8,
	0x39, 0x1f, 0x25, 0xb4, 0xd9, 0x14, 0x89, 0xfe, 0x2f, 0x61, 0xf2, 0x2a, 0xe7, 0x82, 0xfa, 0x15,
	0xac, 0xe9, 0xb2, 0x9b, 0x6b, 0xbe, 0x85, 0x85, 0xd1, 0xd9, 0xfe, 0xc2, 0xe8, 0xc3, 0x47, 0x78,
	0x42, 0xa9, 0x6f, 0xe8, 0x7e, 0xc5, 0x37, 0xff, 0x00, 0x65, 0xe3, 0x50, 0x05, 0xa4, 0x28, 0x7f,
	0x99, 0x87, 0x3e, 0xd6, 0xba, 0xdb, 0x9e, 0x27, 0x6e, 0xae, 0xef, 0x56, 0xf4, 0xaf, 0xdf, 0xff,
	0x0b, 0x00, 0x00, 0xff, 0xff, 0x21, 0x9a, 0xf0, 0xbc, 0xe6, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderServiceClient interface {
	CreateOrder(ctx context.Context, in *OrderGRPCMessage, opts ...grpc.CallOption) (*OrderID, error)
}

type orderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderServiceClient(cc grpc.ClientConnInterface) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) CreateOrder(ctx context.Context, in *OrderGRPCMessage, opts ...grpc.CallOption) (*OrderID, error) {
	out := new(OrderID)
	err := c.cc.Invoke(ctx, "/order.OrderService/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
type OrderServiceServer interface {
	CreateOrder(context.Context, *OrderGRPCMessage) (*OrderID, error)
}

// UnimplementedOrderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOrderServiceServer struct {
}

func (*UnimplementedOrderServiceServer) CreateOrder(ctx context.Context, req *OrderGRPCMessage) (*OrderID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}

func RegisterOrderServiceServer(s *grpc.Server, srv OrderServiceServer) {
	s.RegisterService(&_OrderService_serviceDesc, srv)
}

func _OrderService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderGRPCMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CreateOrder(ctx, req.(*OrderGRPCMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "order.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _OrderService_CreateOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
